Whitelist.create(email: "josefinlnilsson@gmail.com")
Whitelist.create(email: "jossan@drifveriet.se")
Whitelist.create(email: "aron@drifveriet.se")
Whitelist.create(email: "micke@drifveriet.se")
Whitelist.create(email: "nicole@drifveriet.se")
Whitelist.create(email: "agnes@drifveriet.se")
Whitelist.create(email: "hannes@drifveriet.se")
Whitelist.create(email: "joar@drifveriet.se")
Whitelist.create(email: "melvin@drifveriet.se")
Whitelist.create(email: "vilma@drifveriet.se")

Whitelist.create(email: "pontus@drifveriet.se")
Whitelist.create(email: "emmy@drifveriet.se")
Whitelist.create(email: "isabell@drifveriet.se")
Whitelist.create(email: "amanda@drifveriet.se")
Whitelist.create(email: "timas@drifveriet.se")
Whitelist.create(email: "magnus@drifveriet.se")

User.create(email: "josefinlnilsson@gmail.com", name: "Jos", password: "abc123", admin: true)
User.create(email: "jossan@drifveriet.se", name: "Jossan", password: "test123", admin: false)
User.create(email: "aron@drifveriet.se", name: "Aron", password: "test123", admin: false)
User.create(email: "micke@drifveriet.se", name: "Micke", password: "test123", admin: false)
User.create(email: "nicole@drifveriet.se", name: "Nicole", password: "test123", admin: false)
User.create(email: "agnes@drifveriet.se", name: "Agnes", password: "test123", admin: false)
User.create(email: "hannes@drifveriet.se", name: "Hannes", password: "test123", admin: false)
User.create(email: "joar@drifveriet.se", name: "Joar", password: "test123", admin: false)
User.create(email: "melvin@drifveriet.se", name: "Melvin", password: "test123", admin: false)
User.create(email: "vilma@drifveriet.se", name: "Vilma", password: "test123", admin: false)

User.create(email: "pontus@drifveriet.se", name: "Pontus", password: "test123", admin: false)
User.create(email: "emmy@drifveriet.se", name: "Emmy", password: "test123", admin: false)
User.create(email: "isabel@drifveriet.se", name: "Isabel", password: "test123", admin: false)
User.create(email: "amanda@drifveriet.se", name: "Amanda", password: "test123", admin: false)
User.create(email: "timas@drifveriet.se", name: "Timas", password: "test123", admin: false)
User.create(email: "magnus@drifveriet.se", name: "Magnus", password: "test123", admin: false)

Team.create(year: 2018, active: true, users: [1, 2, 3, 4, 5, 6, 7, 8, 9])

