Whitelist.create(email: "josefinlnilsson@gmail.com")
Whitelist.create(email: "jossan@drifveriet.se")
Whitelist.create(email: "aron@drifveriet.se")
Whitelist.create(email: "micke@drifveriet.se")
Whitelist.create(email: "nicole@drifveriet.se")
Whitelist.create(email: "agnes@drifveriet.se")
Whitelist.create(email: "hannes@drifveriet.se")
Whitelist.create(email: "joar@drifveriet.se")
Whitelist.create(email: "melvin@drifveriet.se")
Whitelist.create(email: "vilma@drifveriet.se")
User.create(email: "josefinlnilsson@gmail.com", name: "Jos", password: "abc123", admin: true)
User.create(email: "jossan@drifveriet.se", name: "Jossan", password: "test123", admin: false)
User.create(email: "aron@drifveriet.se", name: "Aron", password: "test123", admin: false)
User.create(email: "micke@drifveriet.se", name: "Micke", password: "test123", admin: false)
User.create(email: "nicole@drifveriet.se", name: "Nicole", password: "test123", admin: false)
User.create(email: "agnes@drifveriet.se", name: "Agnes", password: "test123", admin: false)
User.create(email: "hannes@drifveriet.se", name: "Hannes", password: "test123", admin: false)
User.create(email: "joar@drifveriet.se", name: "Joar", password: "test123", admin: false)
User.create(email: "melvin@drifveriet.se", name: "Melvin", password: "test123", admin: false)
User.create(email: "vilma@drifveriet.se", name: "Vilma", password: "test123", admin: false)